import 'package:flutter/painting.dart';

// Zafe's "Verdigris" palette (docs/brand.md §3), generated by
// `scripts/brand/primitives.js` from `.claude/skills/brand-palette/oklch.js`.
// Edit the generator, not this file.

/// Neutral ladder: 12 steps, each with a dark-mode face (`*Dark`) and a light-mode
/// face (`*Light`). Lightness per step is the previous gray ladder's, measured in
/// OKLCH; chroma is ~1% toward the brand hue (188), so surfaces read as a faint
/// verdigris gray. Semantic tokens under `colors/` pick the face per mode.
///
/// Widgets must never reference these directly. Route through the semantic
/// categories in [AppColors] so roles stay decoupled from the palette.
abstract final class Primitives {
  static const p0Dark = Color(0xFF090D0C);
  static const p0Light = Color(0xFFFFFFFF);

  static const p50Dark = Color(0xFF111515);
  static const p50Light = Color(0xFFF1F5F5);

  static const p100Dark = Color(0xFF161B1B);
  static const p100Light = Color(0xFFE5EAE9);

  static const p150Dark = Color(0xFF1E2323);
  static const p150Light = Color(0xFFD9DFDF);

  static const p200Dark = Color(0xFF272E2D);
  static const p200Light = Color(0xFFC9D0CF);

  static const p300Dark = Color(0xFF353E3D);
  static const p300Light = Color(0xFFABB4B3);

  static const p400Dark = Color(0xFF4E5857);
  static const p400Light = Color(0xFF899392);

  static const p500Dark = Color(0xFF737F7D);
  static const p500Light = Color(0xFF7E8987);

  static const p600Dark = Color(0xFF9DA9A7);
  static const p600Light = Color(0xFF55615F);

  static const p700Dark = Color(0xFFC4CCCB);
  static const p700Light = Color(0xFF3C4645);

  static const p800Dark = Color(0xFFF1F5F5);
  static const p800Light = Color(0xFF131818);

  static const p900Dark = Color(0xFFFFFFFF);
  static const p900Light = Color(0xFF090E0E);

  // Alpha tokens: the ladder steps above at a fixed opacity.
  static const p0Alpha0Dark = Color(0x00090D0C);
  static const p0Alpha0Light = Color(0x00FFFFFF);

  static const p0Alpha5Dark = Color(0x0D090D0C);
  static const p0Alpha5Light = Color(0x0DFFFFFF);

  static const p0Alpha10Dark = Color(0x1A090D0C);
  static const p0Alpha10Light = Color(0x1AFFFFFF);

  static const p0Alpha15Dark = Color(0x26090D0C);
  static const p0Alpha15Light = Color(0x26FFFFFF);

  static const p0Alpha30Dark = Color(0x4D090D0C);
  static const p0Alpha30Light = Color(0x4DFFFFFF);

  static const p0Alpha50Dark = Color(0x80090D0C);
  static const p0Alpha50Light = Color(0x80FFFFFF);

  static const p150Alpha15Dark = Color(0x261E2323);
  static const p150Alpha15Light = Color(0x26D9DFDF);

  static const p300Alpha10Dark = Color(0x1A353E3D);
  static const p300Alpha10Light = Color(0x1AABB4B3);

  static const p300Alpha15Dark = Color(0x26353E3D);
  static const p300Alpha15Light = Color(0x26ABB4B3);

  static const p300Alpha20Dark = Color(0x33353E3D);
  static const p300Alpha20Light = Color(0x33ABB4B3);

  static const p300Alpha35Dark = Color(0x59353E3D);
  static const p300Alpha35Light = Color(0x59ABB4B3);

  static const p300Alpha50Dark = Color(0x80353E3D);
  static const p300Alpha50Light = Color(0x80ABB4B3);

  static const p400Alpha20Dark = Color(0x334E5857);
  static const p400Alpha20Light = Color(0x33899392);

  static const p400Alpha35Dark = Color(0x594E5857);
  static const p400Alpha35Light = Color(0x59899392);

  static const p500Alpha50Dark = Color(0x80737F7D);
  static const p500Alpha50Light = Color(0x807E8987);

  static const p700Alpha50Dark = Color(0x80C4CCCB);
  static const p700Alpha50Light = Color(0x803C4645);

  static const p900Alpha5Dark = Color(0x0DFFFFFF);
  static const p900Alpha5Light = Color(0x0D090E0E);

  static const p900Alpha10Dark = Color(0x1AFFFFFF);
  static const p900Alpha10Light = Color(0x1A090E0E);

  static const p900Alpha20Dark = Color(0x33FFFFFF);
  static const p900Alpha20Light = Color(0x33090E0E);

  static const p900Alpha50Dark = Color(0x80FFFFFF);
  static const p900Alpha50Light = Color(0x80090E0E);
}

/// Brand ladder: verdigris (OKLCH hue 188). Primary buttons, brand text and icons,
/// "needs you", focus rings. Dark p400 #51DDD2 and light p300 #00736C are the accents.
abstract final class BrandPrimitives {
  static const p0Dark = Color(0xFF00110F);
  static const p0Light = Color(0xFFEBFFFD);

  static const p50Dark = Color(0xFF001B19);
  static const p50Light = Color(0xFFBEFFF8);

  static const p100Dark = Color(0xFF002825);
  static const p100Light = Color(0xFF9EF4EC);

  static const p150Dark = Color(0xFF003633);
  static const p150Light = Color(0xFF84E1D9);

  static const p200Dark = Color(0xFF004743);
  static const p200Light = Color(0xFF47B9B0);

  static const p300Dark = Color(0xFF006660);
  static const p300Light = Color(0xFF00736C);

  static const p400Dark = Color(0xFF51DDD2);
  static const p400Light = Color(0xFF00605A);

  static const p500Dark = Color(0xFF61EADF);
  static const p500Light = Color(0xFF004D49);

  static const p600Dark = Color(0xFF70F8ED);
  static const p600Light = Color(0xFF003C38);

  static const p700Dark = Color(0xFF8EFFF5);
  static const p700Light = Color(0xFF002B28);

  static const p800Dark = Color(0xFFC7FFF9);
  static const p800Light = Color(0xFF001B19);

  static const p900Dark = Color(0xFFEBFFFD);
  static const p900Light = Color(0xFF000C0B);

  static const p300Alpha10Dark = Color(0x1A006660);
  static const p300Alpha10Light = Color(0x1A00736C);

  static const p300Alpha15Dark = Color(0x26006660);
  static const p300Alpha15Light = Color(0x2600736C);

  static const p300Alpha25Dark = Color(0x40006660);
  static const p300Alpha25Light = Color(0x4000736C);

  static const p300Alpha35Dark = Color(0x59006660);
  static const p300Alpha35Light = Color(0x5900736C);

  static const p400Alpha15Dark = Color(0x2651DDD2);
  static const p400Alpha15Light = Color(0x2600605A);

  static const p400Alpha25Dark = Color(0x4051DDD2);
  static const p400Alpha25Light = Color(0x4000605A);

  static const p400Alpha35Dark = Color(0x5951DDD2);
  static const p400Alpha35Light = Color(0x5900605A);
}

/// Error ladder: rose (hue 350). Destructive actions and validation errors.
/// Dark p500 #E96CAD and light p300 #A82571 are the text colours.
abstract final class PlumPrimitives {
  static const p0Dark = Color(0xFF14020A);
  static const p0Light = Color(0xFFFFE9F3);

  static const p50Dark = Color(0xFF3B0D27);
  static const p50Light = Color(0xFFFFC4DE);

  static const p100Dark = Color(0xFF5E1B40);
  static const p100Light = Color(0xFFF99CC9);

  static const p150Dark = Color(0xFF6F224C);
  static const p150Light = Color(0xFFEE88BA);

  static const p200Dark = Color(0xFF872C5E);
  static const p200Light = Color(0xFFE273AC);

  static const p300Dark = Color(0xFFA43874);
  static const p300Light = Color(0xFFA82571);

  static const p400Dark = Color(0xFFCA488F);
  static const p400Light = Color(0xFF892D60);

  static const p500Dark = Color(0xFFE96CAD);
  static const p500Light = Color(0xFF752551);

  static const p600Dark = Color(0xFFEE88BA);
  static const p600Light = Color(0xFF5D1B3F);

  static const p700Dark = Color(0xFFF99CC9);
  static const p700Light = Color(0xFF46112F);

  static const p800Dark = Color(0xFFFFC4DE);
  static const p800Light = Color(0xFF31091F);

  static const p900Dark = Color(0xFFFFE9F3);
  static const p900Light = Color(0xFF14020A);

  static const p400Alpha4Dark = Color(0x0ACA488F);
  static const p400Alpha4Light = Color(0x0A892D60);

  static const p400Alpha8Dark = Color(0x14CA488F);
  static const p400Alpha8Light = Color(0x14892D60);

  static const p400Alpha15Dark = Color(0x26CA488F);
  static const p400Alpha15Light = Color(0x26892D60);

  static const p400Alpha25Dark = Color(0x40CA488F);
  static const p400Alpha25Light = Color(0x40892D60);
}

/// Value ladder: Zcash gold (hue 83). Money arriving, amounts' ticker, success,
/// keys and funds (same meaning as the illustrations). Dark p500 #F3BA3C and light
/// p400 #835A00 are the text colours; dark p800 / light p500 are the sync text.
abstract final class GoldPrimitives {
  static const p0Dark = Color(0xFF0D0A05);
  static const p0Light = Color(0xFFFFF8EC);

  static const p50Dark = Color(0xFF14110B);
  static const p50Light = Color(0xFFFFEBCC);

  static const p100Dark = Color(0xFF1E1B15);
  static const p100Light = Color(0xFFFFDCA1);

  static const p150Dark = Color(0xFF30281B);
  static const p150Light = Color(0xFFFFCB70);

  static const p200Dark = Color(0xFF473A21);
  static const p200Light = Color(0xFFF0B135);

  static const p300Dark = Color(0xFF685227);
  static const p300Light = Color(0xFFC79533);

  static const p400Dark = Color(0xFFA5802F);
  static const p400Light = Color(0xFF835A00);

  static const p500Dark = Color(0xFFF3BA3C);
  static const p500Light = Color(0xFF65470F);

  static const p600Dark = Color(0xFFFFCC65);
  static const p600Light = Color(0xFF493B21);

  static const p700Dark = Color(0xFFFFDC9B);
  static const p700Light = Color(0xFF362C1C);

  static const p800Dark = Color(0xFFFFECC9);
  static const p800Light = Color(0xFF1E1B15);

  static const p900Dark = Color(0xFFFFF8EB);
  static const p900Light = Color(0xFF0D0A05);

  static const p300Alpha15Dark = Color(0x26685227);
  static const p300Alpha15Light = Color(0x26C79533);

  static const p300Alpha25Dark = Color(0x40685227);
  static const p300Alpha25Light = Color(0x40C79533);

  static const p300Alpha35Dark = Color(0x59685227);
  static const p300Alpha35Light = Color(0x59C79533);

  static const p400Alpha15Dark = Color(0x26A5802F);
  static const p400Alpha15Light = Color(0x26835A00);

  static const p400Alpha25Dark = Color(0x40A5802F);
  static const p400Alpha25Light = Color(0x40835A00);

  static const p400Alpha35Dark = Color(0x59A5802F);
  static const p400Alpha35Light = Color(0x59835A00);

  static const p500Alpha15Dark = Color(0x26F3BA3C);
  static const p500Alpha15Light = Color(0x2665470F);

  static const p900Alpha50Dark = Color(0x80FFF8EB);
  static const p900Alpha50Light = Color(0x800D0A05);

  static const p900Alpha65Dark = Color(0xA6FFF8EB);
  static const p900Alpha65Light = Color(0xA60D0A05);
}

/// Warning ladder: orange (hue 50, 35°+ from the brand and from gold).
/// Dark p500 #FFAE81 and light p400 #A55115 are the text colours.
abstract final class OrangePrimitives {
  static const p0Dark = Color(0xFF0E0906);
  static const p0Light = Color(0xFFFFF7F3);

  static const p50Dark = Color(0xFF16100C);
  static const p50Light = Color(0xFFFFE9DE);

  static const p100Dark = Color(0xFF231812);
  static const p100Light = Color(0xFFFFD8C3);

  static const p150Dark = Color(0xFF382419);
  static const p150Light = Color(0xFFFFC6A7);

  static const p200Dark = Color(0xFF513322);
  static const p200Light = Color(0xFFFFA571);

  static const p300Dark = Color(0xFF76492F);
  static const p300Light = Color(0xFFDE8550);

  static const p400Dark = Color(0xFFBB7145);
  static const p400Light = Color(0xFFA55115);

  static const p500Dark = Color(0xFFFFAE81);
  static const p500Light = Color(0xFF6A422B);

  static const p600Dark = Color(0xFFFFC6A7);
  static const p600Light = Color(0xFF533523);

  static const p700Dark = Color(0xFFFFD8C3);
  static const p700Light = Color(0xFF3E281C);

  static const p800Dark = Color(0xFFFFE9DE);
  static const p800Light = Color(0xFF231812);

  static const p900Dark = Color(0xFFFFF7F3);
  static const p900Light = Color(0xFF0E0906);

  static const p400Alpha15Dark = Color(0x26BB7145);
  static const p400Alpha15Light = Color(0x26A55115);

  static const p400Alpha25Dark = Color(0x40BB7145);
  static const p400Alpha25Light = Color(0x40A55115);
}
