// Generates app/lib/src/core/theme/primitives.dart (Verdigris, docs/brand.md §3).
// Run: node scripts/brand/primitives.js
const path = require('path');
const { oklch, hexToOklch } = require(path.resolve(__dirname, '../../.claude/skills/brand-palette/oklch.js'));
const out = path.resolve(__dirname, '../../app/lib/src/core/theme/primitives.dart');
const H = 188, T = 0.01;
const steps = ['0', '50', '100', '150', '200', '300', '400', '500', '600', '700', '800', '900'];
const n = (L, m) => oklch(L, T * m, H);

// Neutrals: the old ladder's OKLCH lightness per step, ~1% brand chroma; doc tokens pinned.
const neutralDark = {
  0: n(0.154, 0.6), 50: '#111515', 100: n(0.218, 0.75), 150: '#1E2323', 200: '#272E2D',
  300: n(0.356, 1.2), 400: n(0.452, 1.3), 500: '#737F7D', 600: '#9DA9A7', 700: n(0.838, 0.9),
  800: '#F1F5F5', 900: '#FFFFFF',
};
const neutralLight = {
  0: '#FFFFFF', 50: '#F1F5F5', 100: '#E5EAE9', 150: '#D9DFDF', 200: n(0.853, 0.8),
  300: n(0.762, 1.0), 400: n(0.655, 1.2), 500: '#7E8987', 600: '#55615F', 700: n(0.386, 1.3),
  800: n(0.205, 0.8), 900: '#090E0E',
};
// Brand ramp exactly as docs/brand.md.
const brandDark = ['#00110F', '#001B19', '#002825', '#003633', '#004743', '#006660', '#51DDD2', '#61EADF', '#70F8ED', '#8EFFF5', '#C7FFF9', '#EBFFFD'];
const brandLight = ['#EBFFFD', '#BEFFF8', '#9EF4EC', '#84E1D9', '#47B9B0', '#00736C', '#00605A', '#004D49', '#003C38', '#002B28', '#001B19', '#000C0B'];

/** A 12-step hue ladder: lightness per step, chroma peaking around `peakL`, anchors pinned. */
function ladder(hue, Ls, peakC, peakL, anchors) {
  return Ls.map((L, i) => anchors[steps[i]] ?? oklch(L, Math.max(0.012, peakC * (1 - Math.abs(L - peakL) * 1.6)), hue));
}
const goldLd = [0.145, 0.178, 0.222, 0.282, 0.354, 0.452, 0.62, 0.82, 0.87, 0.91, 0.949, 0.981];
const goldLl = [0.981, 0.949, 0.91, 0.87, 0.8, 0.7, 0.5, 0.421, 0.36, 0.3, 0.222, 0.145];
const roseLd = [0.134, 0.249, 0.341, 0.385, 0.445, 0.514, 0.6, 0.7, 0.75, 0.8, 0.88, 0.955];
const roseLl = [0.955, 0.88, 0.8, 0.75, 0.7, 0.5, 0.45, 0.4, 0.34, 0.28, 0.22, 0.134];

const gold = { d: ladder(83, goldLd, 0.15, 0.8, { 500: '#F3BA3C', 800: '#FFECC9' }), l: ladder(80, goldLl, 0.15, 0.8, { 400: '#835A00', 500: '#65470F' }) };
const orange = { d: ladder(50, goldLd, 0.14, 0.75, { 500: '#FFAE81' }), l: ladder(50, goldLl, 0.14, 0.75, { 400: '#A55115' }) };
const rose = { d: ladder(350, roseLd, 0.18, 0.6, { 500: '#E96CAD' }), l: ladder(350, roseLl, 0.18, 0.6, { 300: '#A82571' }) };

const c = (hex, a = 'FF') => `Color(0x${a}${hex.slice(1)})`;
const alpha = pct => Math.round(pct / 100 * 255).toString(16).toUpperCase().padStart(2, '0');
const lines = [];
const emit = s => lines.push(s);
function pairs(name, d, l) {
  steps.forEach((s, i) => {
    emit(`  static const p${s}Dark = ${c(Array.isArray(d) ? d[i] : d[s])};`);
    emit(`  static const p${s}Light = ${c(Array.isArray(l) ? l[i] : l[s])};`);
    emit('');
  });
}
function alphas(d, l, list) {
  for (const [step, pct] of list) {
    const i = steps.indexOf(String(step));
    const dh = Array.isArray(d) ? d[i] : d[step], lh = Array.isArray(l) ? l[i] : l[step];
    emit(`  static const p${step}Alpha${pct}Dark = ${c(dh, alpha(pct))};`);
    emit(`  static const p${step}Alpha${pct}Light = ${c(lh, alpha(pct))};`);
    emit('');
  }
}

emit(`import 'package:flutter/painting.dart';

// Zafe's "Verdigris" palette (docs/brand.md §3), generated by
// \`scripts/brand/primitives.js\` from \`.claude/skills/brand-palette/oklch.js\`.
// Edit the generator, not this file.

/// Neutral ladder: 12 steps, each with a dark-mode face (\`*Dark\`) and a light-mode
/// face (\`*Light\`). Lightness per step is the previous gray ladder's, measured in
/// OKLCH; chroma is ~1% toward the brand hue (188), so surfaces read as a faint
/// verdigris gray. Semantic tokens under \`colors/\` pick the face per mode.
///
/// Widgets must never reference these directly. Route through the semantic
/// categories in [AppColors] so roles stay decoupled from the palette.
abstract final class Primitives {`);
pairs('n', neutralDark, neutralLight);
emit(`  // Alpha tokens: the ladder steps above at a fixed opacity.`);
alphas(neutralDark, neutralLight, [[0, 0], [0, 5], [0, 10], [0, 15], [0, 30], [0, 50], [150, 15], [300, 10], [300, 15], [300, 20], [300, 35], [300, 50], [400, 20], [400, 35], [500, 50], [700, 50], [900, 5], [900, 10], [900, 20], [900, 50]]);
lines.pop();
emit(`}

/// Brand ladder: verdigris (OKLCH hue 188). Primary buttons, brand text and icons,
/// "needs you", focus rings. Dark p400 #51DDD2 and light p300 #00736C are the accents.
abstract final class BrandPrimitives {`);
pairs('b', brandDark, brandLight);
alphas(brandDark, brandLight, [[300, 10], [300, 15], [300, 25], [300, 35], [400, 15], [400, 25], [400, 35]]);
lines.pop();
emit(`}

/// Error ladder: rose (hue 350). Destructive actions and validation errors.
/// Dark p500 #E96CAD and light p300 #A82571 are the text colours.
abstract final class RosePrimitives {`);
pairs('r', rose.d, rose.l);
alphas(rose.d, rose.l, [[400, 4], [400, 8], [400, 15], [400, 25]]);
lines.pop();
emit(`}

/// Value ladder: Zcash gold (hue 83). Money arriving, amounts' ticker, success,
/// keys and funds (same meaning as the illustrations). Dark p500 #F3BA3C and light
/// p400 #835A00 are the text colours; dark p800 / light p500 are the sync text.
abstract final class GoldPrimitives {`);
pairs('g', gold.d, gold.l);
alphas(gold.d, gold.l, [[300, 15], [300, 25], [300, 35], [400, 15], [400, 25], [400, 35], [500, 15], [900, 50], [900, 65]]);
lines.pop();
emit(`}

/// Warning ladder: orange (hue 50, 35°+ from the brand and from gold).
/// Dark p500 #FFAE81 and light p400 #A55115 are the text colours.
abstract final class OrangePrimitives {`);
pairs('o', orange.d, orange.l);
alphas(orange.d, orange.l, [[400, 15], [400, 25]]);
lines.pop();
emit('}');
require('fs').writeFileSync(out, lines.join('\n') + '\n');
