// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/vault.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiAppInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -649286018;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_zafe',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiVaultCreateVault({
    required String relayUrl,
    required List<int> seeds,
    required String name,
    required int threshold,
    required int members,
  });

  IdentityInfo crateApiVaultGenerateIdentity();

  String crateApiVaultIdentityPublicKey({required List<int> seeds});

  Future<void> crateApiAppInitApp();

  Future<void> crateApiVaultJoinVault({
    required String relayUrl,
    required List<int> seeds,
    required String invite,
  });

  InviteInfo crateApiVaultParseInvite({required String invite});

  Future<Uint8List> crateApiVaultRunKeygen({
    required String relayUrl,
    required String lightwalletdUrl,
    required String networkName,
    required List<int> seeds,
    required String invite,
    required String confirmedSafetyNumber,
    required int timeoutSecs,
  });

  Future<void> crateApiVaultSealVault({
    required String relayUrl,
    required List<int> seeds,
    required String invite,
  });

  Future<Balance> crateApiVaultSyncVault({
    required String dbDir,
    required String lightwalletdUrl,
    required List<int> material,
  });

  Future<MembershipInfo> crateApiVaultVaultMembership({
    required String relayUrl,
    required List<int> seeds,
    required String invite,
  });

  VaultSummary crateApiVaultVaultSummary({required List<int> material});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiVaultCreateVault({
    required String relayUrl,
    required List<int> seeds,
    required String name,
    required int threshold,
    required int members,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(relayUrl, serializer);
          sse_encode_list_prim_u_8_loose(seeds, serializer);
          sse_encode_String(name, serializer);
          sse_encode_u_16(threshold, serializer);
          sse_encode_u_16(members, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultCreateVaultConstMeta,
        argValues: [relayUrl, seeds, name, threshold, members],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultCreateVaultConstMeta => const TaskConstMeta(
    debugName: "create_vault",
    argNames: ["relayUrl", "seeds", "name", "threshold", "members"],
  );

  @override
  IdentityInfo crateApiVaultGenerateIdentity() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultGenerateIdentityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultGenerateIdentityConstMeta =>
      const TaskConstMeta(debugName: "generate_identity", argNames: []);

  @override
  String crateApiVaultIdentityPublicKey({required List<int> seeds}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(seeds, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultIdentityPublicKeyConstMeta,
        argValues: [seeds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultIdentityPublicKeyConstMeta =>
      const TaskConstMeta(
        debugName: "identity_public_key",
        argNames: ["seeds"],
      );

  @override
  Future<void> crateApiAppInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiVaultJoinVault({
    required String relayUrl,
    required List<int> seeds,
    required String invite,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(relayUrl, serializer);
          sse_encode_list_prim_u_8_loose(seeds, serializer);
          sse_encode_String(invite, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultJoinVaultConstMeta,
        argValues: [relayUrl, seeds, invite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultJoinVaultConstMeta => const TaskConstMeta(
    debugName: "join_vault",
    argNames: ["relayUrl", "seeds", "invite"],
  );

  @override
  InviteInfo crateApiVaultParseInvite({required String invite}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(invite, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_invite_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultParseInviteConstMeta,
        argValues: [invite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultParseInviteConstMeta =>
      const TaskConstMeta(debugName: "parse_invite", argNames: ["invite"]);

  @override
  Future<Uint8List> crateApiVaultRunKeygen({
    required String relayUrl,
    required String lightwalletdUrl,
    required String networkName,
    required List<int> seeds,
    required String invite,
    required String confirmedSafetyNumber,
    required int timeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(relayUrl, serializer);
          sse_encode_String(lightwalletdUrl, serializer);
          sse_encode_String(networkName, serializer);
          sse_encode_list_prim_u_8_loose(seeds, serializer);
          sse_encode_String(invite, serializer);
          sse_encode_String(confirmedSafetyNumber, serializer);
          sse_encode_u_32(timeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultRunKeygenConstMeta,
        argValues: [
          relayUrl,
          lightwalletdUrl,
          networkName,
          seeds,
          invite,
          confirmedSafetyNumber,
          timeoutSecs,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultRunKeygenConstMeta => const TaskConstMeta(
    debugName: "run_keygen",
    argNames: [
      "relayUrl",
      "lightwalletdUrl",
      "networkName",
      "seeds",
      "invite",
      "confirmedSafetyNumber",
      "timeoutSecs",
    ],
  );

  @override
  Future<void> crateApiVaultSealVault({
    required String relayUrl,
    required List<int> seeds,
    required String invite,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(relayUrl, serializer);
          sse_encode_list_prim_u_8_loose(seeds, serializer);
          sse_encode_String(invite, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultSealVaultConstMeta,
        argValues: [relayUrl, seeds, invite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultSealVaultConstMeta => const TaskConstMeta(
    debugName: "seal_vault",
    argNames: ["relayUrl", "seeds", "invite"],
  );

  @override
  Future<Balance> crateApiVaultSyncVault({
    required String dbDir,
    required String lightwalletdUrl,
    required List<int> material,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbDir, serializer);
          sse_encode_String(lightwalletdUrl, serializer);
          sse_encode_list_prim_u_8_loose(material, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_balance,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultSyncVaultConstMeta,
        argValues: [dbDir, lightwalletdUrl, material],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultSyncVaultConstMeta => const TaskConstMeta(
    debugName: "sync_vault",
    argNames: ["dbDir", "lightwalletdUrl", "material"],
  );

  @override
  Future<MembershipInfo> crateApiVaultVaultMembership({
    required String relayUrl,
    required List<int> seeds,
    required String invite,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(relayUrl, serializer);
          sse_encode_list_prim_u_8_loose(seeds, serializer);
          sse_encode_String(invite, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_membership_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultVaultMembershipConstMeta,
        argValues: [relayUrl, seeds, invite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultMembershipConstMeta =>
      const TaskConstMeta(
        debugName: "vault_membership",
        argNames: ["relayUrl", "seeds", "invite"],
      );

  @override
  VaultSummary crateApiVaultVaultSummary({required List<int> material}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(material, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultVaultSummaryConstMeta,
        argValues: [material],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultSummaryConstMeta =>
      const TaskConstMeta(debugName: "vault_summary", argNames: ["material"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Balance dco_decode_balance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Balance(
      height: dco_decode_u_32(arr[0]),
      spendableZat: dco_decode_u_64(arr[1]),
      totalZat: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  IdentityInfo dco_decode_identity_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return IdentityInfo(
      seeds: dco_decode_list_prim_u_8_strict(arr[0]),
      publicKeyHex: dco_decode_String(arr[1]),
    );
  }

  @protected
  InviteInfo dco_decode_invite_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return InviteInfo(
      name: dco_decode_String(arr[0]),
      threshold: dco_decode_u_16(arr[1]),
      members: dco_decode_u_16(arr[2]),
      creatorHex: dco_decode_String(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MembershipInfo dco_decode_membership_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MembershipInfo(
      members: dco_decode_list_String(arr[0]),
      sealed: dco_decode_bool(arr[1]),
      safetyNumber: dco_decode_String(arr[2]),
      isCreator: dco_decode_bool(arr[3]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VaultSummary dco_decode_vault_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return VaultSummary(
      name: dco_decode_String(arr[0]),
      network: dco_decode_String(arr[1]),
      address: dco_decode_String(arr[2]),
      threshold: dco_decode_u_16(arr[3]),
      members: dco_decode_list_String(arr[4]),
      birthdayHeight: dco_decode_u_32(arr[5]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Balance sse_decode_balance(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_height = sse_decode_u_32(deserializer);
    var var_spendableZat = sse_decode_u_64(deserializer);
    var var_totalZat = sse_decode_u_64(deserializer);
    return Balance(
      height: var_height,
      spendableZat: var_spendableZat,
      totalZat: var_totalZat,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  IdentityInfo sse_decode_identity_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_seeds = sse_decode_list_prim_u_8_strict(deserializer);
    var var_publicKeyHex = sse_decode_String(deserializer);
    return IdentityInfo(seeds: var_seeds, publicKeyHex: var_publicKeyHex);
  }

  @protected
  InviteInfo sse_decode_invite_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_threshold = sse_decode_u_16(deserializer);
    var var_members = sse_decode_u_16(deserializer);
    var var_creatorHex = sse_decode_String(deserializer);
    return InviteInfo(
      name: var_name,
      threshold: var_threshold,
      members: var_members,
      creatorHex: var_creatorHex,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MembershipInfo sse_decode_membership_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_members = sse_decode_list_String(deserializer);
    var var_sealed = sse_decode_bool(deserializer);
    var var_safetyNumber = sse_decode_String(deserializer);
    var var_isCreator = sse_decode_bool(deserializer);
    return MembershipInfo(
      members: var_members,
      sealed: var_sealed,
      safetyNumber: var_safetyNumber,
      isCreator: var_isCreator,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VaultSummary sse_decode_vault_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_network = sse_decode_String(deserializer);
    var var_address = sse_decode_String(deserializer);
    var var_threshold = sse_decode_u_16(deserializer);
    var var_members = sse_decode_list_String(deserializer);
    var var_birthdayHeight = sse_decode_u_32(deserializer);
    return VaultSummary(
      name: var_name,
      network: var_network,
      address: var_address,
      threshold: var_threshold,
      members: var_members,
      birthdayHeight: var_birthdayHeight,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_balance(Balance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.height, serializer);
    sse_encode_u_64(self.spendableZat, serializer);
    sse_encode_u_64(self.totalZat, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_identity_info(IdentityInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.seeds, serializer);
    sse_encode_String(self.publicKeyHex, serializer);
  }

  @protected
  void sse_encode_invite_info(InviteInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_16(self.threshold, serializer);
    sse_encode_u_16(self.members, serializer);
    sse_encode_String(self.creatorHex, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_membership_info(
    MembershipInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.members, serializer);
    sse_encode_bool(self.sealed, serializer);
    sse_encode_String(self.safetyNumber, serializer);
    sse_encode_bool(self.isCreator, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_vault_summary(VaultSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.network, serializer);
    sse_encode_String(self.address, serializer);
    sse_encode_u_16(self.threshold, serializer);
    sse_encode_list_String(self.members, serializer);
    sse_encode_u_32(self.birthdayHeight, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
