// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/error.dart';
import 'api/proposals.dart';
import 'api/vault.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiAppInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1377004119;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_zafe',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<int> crateApiProposalsAnswerSigningRequests({
    required String relayUrl,
    required String lightwalletdUrl,
    required String dbDir,
    required String stateDir,
    required List<int> seeds,
    required List<int> material,
  });

  Future<ApproveResult> crateApiProposalsApproveProposal({
    required String relayUrl,
    required String lightwalletdUrl,
    required String dbDir,
    required String stateDir,
    required List<int> seeds,
    required List<int> material,
    required String proposalId,
  });

  AddressCheck crateApiProposalsCheckAddress({
    required String networkName,
    required String address,
  });

  Future<String> crateApiVaultCreateVault({
    required String relayUrl,
    required List<int> seeds,
    required String name,
    required int threshold,
    required int members,
  });

  IdentityInfo crateApiVaultGenerateIdentity();

  String crateApiVaultIdentityPublicKey({required List<int> seeds});

  Future<void> crateApiAppInitApp();

  Future<void> crateApiVaultJoinVault({
    required String relayUrl,
    required List<int> seeds,
    required String invite,
  });

  Future<List<ProposalInfo>> crateApiProposalsListProposals({
    required String relayUrl,
    required String stateDir,
    required List<int> seeds,
    required List<int> material,
  });

  int crateApiProposalsMemoLength({required String memo});

  InviteInfo crateApiVaultParseInvite({required String invite});

  BigInt? crateApiProposalsParseZec({required String text});

  Future<String> crateApiProposalsProposePayment({
    required String relayUrl,
    required String lightwalletdUrl,
    required String dbDir,
    required List<int> seeds,
    required List<int> material,
    required List<PaymentInput> payments,
    required bool autoSend,
  });

  Future<void> crateApiVaultRegisterPush({
    required String relayUrl,
    required List<int> seeds,
    required List<int> material,
    required String platform,
    required String token,
  });

  Future<void> crateApiProposalsRejectProposal({
    required String relayUrl,
    required List<int> seeds,
    required List<int> material,
    required String proposalId,
  });

  Future<ReviewInfo> crateApiProposalsReviewProposal({
    required String relayUrl,
    required String lightwalletdUrl,
    required String dbDir,
    required List<int> seeds,
    required List<int> material,
    required String proposalId,
  });

  Future<Uint8List> crateApiVaultRunKeygen({
    required String relayUrl,
    required String lightwalletdUrl,
    required String networkName,
    required List<int> seeds,
    required String invite,
    required String confirmedSafetyNumber,
    required int timeoutSecs,
    int? birthdayHeight,
  });

  Future<void> crateApiVaultSealVault({
    required String relayUrl,
    required List<int> seeds,
    required String invite,
  });

  Stream<SendProgress> crateApiProposalsSendProposal({
    required String relayUrl,
    required String lightwalletdUrl,
    required String dbDir,
    required String stateDir,
    required List<int> seeds,
    required List<int> material,
    required String proposalId,
  });

  Future<Balance> crateApiVaultSyncVault({
    required String dbDir,
    required String lightwalletdUrl,
    required List<int> material,
  });

  Future<MembershipInfo> crateApiVaultVaultMembership({
    required String relayUrl,
    required List<int> seeds,
    required String invite,
  });

  VaultSummary crateApiVaultVaultSummary({required List<int> material});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<int> crateApiProposalsAnswerSigningRequests({
    required String relayUrl,
    required String lightwalletdUrl,
    required String dbDir,
    required String stateDir,
    required List<int> seeds,
    required List<int> material,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(relayUrl, serializer);
          sse_encode_String(lightwalletdUrl, serializer);
          sse_encode_String(dbDir, serializer);
          sse_encode_String(stateDir, serializer);
          sse_encode_list_prim_u_8_loose(seeds, serializer);
          sse_encode_list_prim_u_8_loose(material, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_zafe_error,
        ),
        constMeta: kCrateApiProposalsAnswerSigningRequestsConstMeta,
        argValues: [
          relayUrl,
          lightwalletdUrl,
          dbDir,
          stateDir,
          seeds,
          material,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProposalsAnswerSigningRequestsConstMeta =>
      const TaskConstMeta(
        debugName: "answer_signing_requests",
        argNames: [
          "relayUrl",
          "lightwalletdUrl",
          "dbDir",
          "stateDir",
          "seeds",
          "material",
        ],
      );

  @override
  Future<ApproveResult> crateApiProposalsApproveProposal({
    required String relayUrl,
    required String lightwalletdUrl,
    required String dbDir,
    required String stateDir,
    required List<int> seeds,
    required List<int> material,
    required String proposalId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(relayUrl, serializer);
          sse_encode_String(lightwalletdUrl, serializer);
          sse_encode_String(dbDir, serializer);
          sse_encode_String(stateDir, serializer);
          sse_encode_list_prim_u_8_loose(seeds, serializer);
          sse_encode_list_prim_u_8_loose(material, serializer);
          sse_encode_String(proposalId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_approve_result,
          decodeErrorData: sse_decode_zafe_error,
        ),
        constMeta: kCrateApiProposalsApproveProposalConstMeta,
        argValues: [
          relayUrl,
          lightwalletdUrl,
          dbDir,
          stateDir,
          seeds,
          material,
          proposalId,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProposalsApproveProposalConstMeta =>
      const TaskConstMeta(
        debugName: "approve_proposal",
        argNames: [
          "relayUrl",
          "lightwalletdUrl",
          "dbDir",
          "stateDir",
          "seeds",
          "material",
          "proposalId",
        ],
      );

  @override
  AddressCheck crateApiProposalsCheckAddress({
    required String networkName,
    required String address,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(networkName, serializer);
          sse_encode_String(address, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_address_check,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProposalsCheckAddressConstMeta,
        argValues: [networkName, address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProposalsCheckAddressConstMeta =>
      const TaskConstMeta(
        debugName: "check_address",
        argNames: ["networkName", "address"],
      );

  @override
  Future<String> crateApiVaultCreateVault({
    required String relayUrl,
    required List<int> seeds,
    required String name,
    required int threshold,
    required int members,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(relayUrl, serializer);
          sse_encode_list_prim_u_8_loose(seeds, serializer);
          sse_encode_String(name, serializer);
          sse_encode_u_16(threshold, serializer);
          sse_encode_u_16(members, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_zafe_error,
        ),
        constMeta: kCrateApiVaultCreateVaultConstMeta,
        argValues: [relayUrl, seeds, name, threshold, members],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultCreateVaultConstMeta => const TaskConstMeta(
    debugName: "create_vault",
    argNames: ["relayUrl", "seeds", "name", "threshold", "members"],
  );

  @override
  IdentityInfo crateApiVaultGenerateIdentity() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultGenerateIdentityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultGenerateIdentityConstMeta =>
      const TaskConstMeta(debugName: "generate_identity", argNames: []);

  @override
  String crateApiVaultIdentityPublicKey({required List<int> seeds}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(seeds, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_zafe_error,
        ),
        constMeta: kCrateApiVaultIdentityPublicKeyConstMeta,
        argValues: [seeds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultIdentityPublicKeyConstMeta =>
      const TaskConstMeta(
        debugName: "identity_public_key",
        argNames: ["seeds"],
      );

  @override
  Future<void> crateApiAppInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiVaultJoinVault({
    required String relayUrl,
    required List<int> seeds,
    required String invite,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(relayUrl, serializer);
          sse_encode_list_prim_u_8_loose(seeds, serializer);
          sse_encode_String(invite, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_zafe_error,
        ),
        constMeta: kCrateApiVaultJoinVaultConstMeta,
        argValues: [relayUrl, seeds, invite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultJoinVaultConstMeta => const TaskConstMeta(
    debugName: "join_vault",
    argNames: ["relayUrl", "seeds", "invite"],
  );

  @override
  Future<List<ProposalInfo>> crateApiProposalsListProposals({
    required String relayUrl,
    required String stateDir,
    required List<int> seeds,
    required List<int> material,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(relayUrl, serializer);
          sse_encode_String(stateDir, serializer);
          sse_encode_list_prim_u_8_loose(seeds, serializer);
          sse_encode_list_prim_u_8_loose(material, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_proposal_info,
          decodeErrorData: sse_decode_zafe_error,
        ),
        constMeta: kCrateApiProposalsListProposalsConstMeta,
        argValues: [relayUrl, stateDir, seeds, material],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProposalsListProposalsConstMeta =>
      const TaskConstMeta(
        debugName: "list_proposals",
        argNames: ["relayUrl", "stateDir", "seeds", "material"],
      );

  @override
  int crateApiProposalsMemoLength({required String memo}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(memo, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProposalsMemoLengthConstMeta,
        argValues: [memo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProposalsMemoLengthConstMeta =>
      const TaskConstMeta(debugName: "memo_length", argNames: ["memo"]);

  @override
  InviteInfo crateApiVaultParseInvite({required String invite}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(invite, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_invite_info,
          decodeErrorData: sse_decode_zafe_error,
        ),
        constMeta: kCrateApiVaultParseInviteConstMeta,
        argValues: [invite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultParseInviteConstMeta =>
      const TaskConstMeta(debugName: "parse_invite", argNames: ["invite"]);

  @override
  BigInt? crateApiProposalsParseZec({required String text}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProposalsParseZecConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProposalsParseZecConstMeta =>
      const TaskConstMeta(debugName: "parse_zec", argNames: ["text"]);

  @override
  Future<String> crateApiProposalsProposePayment({
    required String relayUrl,
    required String lightwalletdUrl,
    required String dbDir,
    required List<int> seeds,
    required List<int> material,
    required List<PaymentInput> payments,
    required bool autoSend,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(relayUrl, serializer);
          sse_encode_String(lightwalletdUrl, serializer);
          sse_encode_String(dbDir, serializer);
          sse_encode_list_prim_u_8_loose(seeds, serializer);
          sse_encode_list_prim_u_8_loose(material, serializer);
          sse_encode_list_payment_input(payments, serializer);
          sse_encode_bool(autoSend, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_zafe_error,
        ),
        constMeta: kCrateApiProposalsProposePaymentConstMeta,
        argValues: [
          relayUrl,
          lightwalletdUrl,
          dbDir,
          seeds,
          material,
          payments,
          autoSend,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProposalsProposePaymentConstMeta =>
      const TaskConstMeta(
        debugName: "propose_payment",
        argNames: [
          "relayUrl",
          "lightwalletdUrl",
          "dbDir",
          "seeds",
          "material",
          "payments",
          "autoSend",
        ],
      );

  @override
  Future<void> crateApiVaultRegisterPush({
    required String relayUrl,
    required List<int> seeds,
    required List<int> material,
    required String platform,
    required String token,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(relayUrl, serializer);
          sse_encode_list_prim_u_8_loose(seeds, serializer);
          sse_encode_list_prim_u_8_loose(material, serializer);
          sse_encode_String(platform, serializer);
          sse_encode_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_zafe_error,
        ),
        constMeta: kCrateApiVaultRegisterPushConstMeta,
        argValues: [relayUrl, seeds, material, platform, token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultRegisterPushConstMeta => const TaskConstMeta(
    debugName: "register_push",
    argNames: ["relayUrl", "seeds", "material", "platform", "token"],
  );

  @override
  Future<void> crateApiProposalsRejectProposal({
    required String relayUrl,
    required List<int> seeds,
    required List<int> material,
    required String proposalId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(relayUrl, serializer);
          sse_encode_list_prim_u_8_loose(seeds, serializer);
          sse_encode_list_prim_u_8_loose(material, serializer);
          sse_encode_String(proposalId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_zafe_error,
        ),
        constMeta: kCrateApiProposalsRejectProposalConstMeta,
        argValues: [relayUrl, seeds, material, proposalId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProposalsRejectProposalConstMeta =>
      const TaskConstMeta(
        debugName: "reject_proposal",
        argNames: ["relayUrl", "seeds", "material", "proposalId"],
      );

  @override
  Future<ReviewInfo> crateApiProposalsReviewProposal({
    required String relayUrl,
    required String lightwalletdUrl,
    required String dbDir,
    required List<int> seeds,
    required List<int> material,
    required String proposalId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(relayUrl, serializer);
          sse_encode_String(lightwalletdUrl, serializer);
          sse_encode_String(dbDir, serializer);
          sse_encode_list_prim_u_8_loose(seeds, serializer);
          sse_encode_list_prim_u_8_loose(material, serializer);
          sse_encode_String(proposalId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_review_info,
          decodeErrorData: sse_decode_zafe_error,
        ),
        constMeta: kCrateApiProposalsReviewProposalConstMeta,
        argValues: [
          relayUrl,
          lightwalletdUrl,
          dbDir,
          seeds,
          material,
          proposalId,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProposalsReviewProposalConstMeta =>
      const TaskConstMeta(
        debugName: "review_proposal",
        argNames: [
          "relayUrl",
          "lightwalletdUrl",
          "dbDir",
          "seeds",
          "material",
          "proposalId",
        ],
      );

  @override
  Future<Uint8List> crateApiVaultRunKeygen({
    required String relayUrl,
    required String lightwalletdUrl,
    required String networkName,
    required List<int> seeds,
    required String invite,
    required String confirmedSafetyNumber,
    required int timeoutSecs,
    int? birthdayHeight,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(relayUrl, serializer);
          sse_encode_String(lightwalletdUrl, serializer);
          sse_encode_String(networkName, serializer);
          sse_encode_list_prim_u_8_loose(seeds, serializer);
          sse_encode_String(invite, serializer);
          sse_encode_String(confirmedSafetyNumber, serializer);
          sse_encode_u_32(timeoutSecs, serializer);
          sse_encode_opt_box_autoadd_u_32(birthdayHeight, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_zafe_error,
        ),
        constMeta: kCrateApiVaultRunKeygenConstMeta,
        argValues: [
          relayUrl,
          lightwalletdUrl,
          networkName,
          seeds,
          invite,
          confirmedSafetyNumber,
          timeoutSecs,
          birthdayHeight,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultRunKeygenConstMeta => const TaskConstMeta(
    debugName: "run_keygen",
    argNames: [
      "relayUrl",
      "lightwalletdUrl",
      "networkName",
      "seeds",
      "invite",
      "confirmedSafetyNumber",
      "timeoutSecs",
      "birthdayHeight",
    ],
  );

  @override
  Future<void> crateApiVaultSealVault({
    required String relayUrl,
    required List<int> seeds,
    required String invite,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(relayUrl, serializer);
          sse_encode_list_prim_u_8_loose(seeds, serializer);
          sse_encode_String(invite, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_zafe_error,
        ),
        constMeta: kCrateApiVaultSealVaultConstMeta,
        argValues: [relayUrl, seeds, invite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultSealVaultConstMeta => const TaskConstMeta(
    debugName: "seal_vault",
    argNames: ["relayUrl", "seeds", "invite"],
  );

  @override
  Stream<SendProgress> crateApiProposalsSendProposal({
    required String relayUrl,
    required String lightwalletdUrl,
    required String dbDir,
    required String stateDir,
    required List<int> seeds,
    required List<int> material,
    required String proposalId,
  }) {
    final sink = RustStreamSink<SendProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(relayUrl, serializer);
            sse_encode_String(lightwalletdUrl, serializer);
            sse_encode_String(dbDir, serializer);
            sse_encode_String(stateDir, serializer);
            sse_encode_list_prim_u_8_loose(seeds, serializer);
            sse_encode_list_prim_u_8_loose(material, serializer);
            sse_encode_String(proposalId, serializer);
            sse_encode_StreamSink_send_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 19,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_zafe_error,
          ),
          constMeta: kCrateApiProposalsSendProposalConstMeta,
          argValues: [
            relayUrl,
            lightwalletdUrl,
            dbDir,
            stateDir,
            seeds,
            material,
            proposalId,
            sink,
          ],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiProposalsSendProposalConstMeta =>
      const TaskConstMeta(
        debugName: "send_proposal",
        argNames: [
          "relayUrl",
          "lightwalletdUrl",
          "dbDir",
          "stateDir",
          "seeds",
          "material",
          "proposalId",
          "sink",
        ],
      );

  @override
  Future<Balance> crateApiVaultSyncVault({
    required String dbDir,
    required String lightwalletdUrl,
    required List<int> material,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbDir, serializer);
          sse_encode_String(lightwalletdUrl, serializer);
          sse_encode_list_prim_u_8_loose(material, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_balance,
          decodeErrorData: sse_decode_zafe_error,
        ),
        constMeta: kCrateApiVaultSyncVaultConstMeta,
        argValues: [dbDir, lightwalletdUrl, material],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultSyncVaultConstMeta => const TaskConstMeta(
    debugName: "sync_vault",
    argNames: ["dbDir", "lightwalletdUrl", "material"],
  );

  @override
  Future<MembershipInfo> crateApiVaultVaultMembership({
    required String relayUrl,
    required List<int> seeds,
    required String invite,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(relayUrl, serializer);
          sse_encode_list_prim_u_8_loose(seeds, serializer);
          sse_encode_String(invite, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_membership_info,
          decodeErrorData: sse_decode_zafe_error,
        ),
        constMeta: kCrateApiVaultVaultMembershipConstMeta,
        argValues: [relayUrl, seeds, invite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultMembershipConstMeta =>
      const TaskConstMeta(
        debugName: "vault_membership",
        argNames: ["relayUrl", "seeds", "invite"],
      );

  @override
  VaultSummary crateApiVaultVaultSummary({required List<int> material}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(material, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_summary,
          decodeErrorData: sse_decode_zafe_error,
        ),
        constMeta: kCrateApiVaultVaultSummaryConstMeta,
        argValues: [material],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultSummaryConstMeta =>
      const TaskConstMeta(debugName: "vault_summary", argNames: ["material"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<SendProgress> dco_decode_StreamSink_send_progress_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AddressCheck dco_decode_address_check(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AddressCheck(
      valid: dco_decode_bool(arr[0]),
      reason: dco_decode_String(arr[1]),
    );
  }

  @protected
  ApproveResult dco_decode_approve_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApproveResult(
      signed: dco_decode_bool(arr[0]),
      completed: dco_decode_bool(arr[1]),
      autoSend: dco_decode_bool(arr[2]),
    );
  }

  @protected
  Balance dco_decode_balance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Balance(
      height: dco_decode_u_32(arr[0]),
      spendableZat: dco_decode_u_64(arr[1]),
      totalZat: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  ZafeError dco_decode_box_autoadd_zafe_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_zafe_error(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  IdentityInfo dco_decode_identity_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return IdentityInfo(
      seeds: dco_decode_list_prim_u_8_strict(arr[0]),
      publicKeyHex: dco_decode_String(arr[1]),
    );
  }

  @protected
  InviteInfo dco_decode_invite_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return InviteInfo(
      name: dco_decode_String(arr[0]),
      threshold: dco_decode_u_16(arr[1]),
      members: dco_decode_u_16(arr[2]),
      creatorHex: dco_decode_String(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<PaymentInfo> dco_decode_list_payment_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_payment_info).toList();
  }

  @protected
  List<PaymentInput> dco_decode_list_payment_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_payment_input).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProposalInfo> dco_decode_list_proposal_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_proposal_info).toList();
  }

  @protected
  MembershipInfo dco_decode_membership_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MembershipInfo(
      members: dco_decode_list_String(arr[0]),
      sealed: dco_decode_bool(arr[1]),
      safetyNumber: dco_decode_String(arr[2]),
      isCreator: dco_decode_bool(arr[3]),
    );
  }

  @protected
  MyVote dco_decode_my_vote(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MyVote.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  ZafeError? dco_decode_opt_box_autoadd_zafe_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_zafe_error(raw);
  }

  @protected
  PaymentInfo dco_decode_payment_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PaymentInfo(
      address: dco_decode_String(arr[0]),
      amountZat: dco_decode_u_64(arr[1]),
      memo: dco_decode_String(arr[2]),
    );
  }

  @protected
  PaymentInput dco_decode_payment_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PaymentInput(
      address: dco_decode_String(arr[0]),
      amountZat: dco_decode_u_64(arr[1]),
      memo: dco_decode_String(arr[2]),
    );
  }

  @protected
  ProposalInfo dco_decode_proposal_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 18)
      throw Exception('unexpected arr length: expect 18 but see ${arr.length}');
    return ProposalInfo(
      id: dco_decode_String(arr[0]),
      author: dco_decode_String(arr[1]),
      isMine: dco_decode_bool(arr[2]),
      payments: dco_decode_list_payment_info(arr[3]),
      totalZat: dco_decode_u_64(arr[4]),
      stage: dco_decode_proposal_stage(arr[5]),
      approvals: dco_decode_list_String(arr[6]),
      rejections: dco_decode_list_String(arr[7]),
      myVote: dco_decode_my_vote(arr[8]),
      threshold: dco_decode_u_16(arr[9]),
      rejectionThreshold: dco_decode_u_16(arr[10]),
      createdAt: dco_decode_u_64(arr[11]),
      txid: dco_decode_opt_String(arr[12]),
      signingStarted: dco_decode_bool(arr[13]),
      oneTap: dco_decode_bool(arr[14]),
      ready: dco_decode_bool(arr[15]),
      completedByMe: dco_decode_bool(arr[16]),
      autoSend: dco_decode_bool(arr[17]),
    );
  }

  @protected
  ProposalStage dco_decode_proposal_stage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProposalStage.values[raw as int];
  }

  @protected
  ReviewInfo dco_decode_review_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ReviewInfo(
      verified: dco_decode_bool(arr[0]),
      problem: dco_decode_String(arr[1]),
      feeZat: dco_decode_u_64(arr[2]),
      changeZat: dco_decode_u_64(arr[3]),
      inputZat: dco_decode_u_64(arr[4]),
      spends: dco_decode_u_32(arr[5]),
      expiryHeight: dco_decode_u_32(arr[6]),
      tipHeight: dco_decode_u_32(arr[7]),
    );
  }

  @protected
  SendProgress dco_decode_send_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SendProgress(
      stage: dco_decode_send_stage(arr[0]),
      received: dco_decode_u_32(arr[1]),
      needed: dco_decode_u_32(arr[2]),
      txid: dco_decode_opt_String(arr[3]),
      error: dco_decode_opt_box_autoadd_zafe_error(arr[4]),
    );
  }

  @protected
  SendStage dco_decode_send_stage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SendStage.values[raw as int];
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VaultSummary dco_decode_vault_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return VaultSummary(
      name: dco_decode_String(arr[0]),
      network: dco_decode_String(arr[1]),
      address: dco_decode_String(arr[2]),
      threshold: dco_decode_u_16(arr[3]),
      members: dco_decode_list_String(arr[4]),
      birthdayHeight: dco_decode_u_32(arr[5]),
    );
  }

  @protected
  ZafeError dco_decode_zafe_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ZafeError(
      kind: dco_decode_zafe_error_kind(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  ZafeErrorKind dco_decode_zafe_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ZafeErrorKind.values[raw as int];
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<SendProgress> sse_decode_StreamSink_send_progress_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AddressCheck sse_decode_address_check(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_valid = sse_decode_bool(deserializer);
    var var_reason = sse_decode_String(deserializer);
    return AddressCheck(valid: var_valid, reason: var_reason);
  }

  @protected
  ApproveResult sse_decode_approve_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_signed = sse_decode_bool(deserializer);
    var var_completed = sse_decode_bool(deserializer);
    var var_autoSend = sse_decode_bool(deserializer);
    return ApproveResult(
      signed: var_signed,
      completed: var_completed,
      autoSend: var_autoSend,
    );
  }

  @protected
  Balance sse_decode_balance(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_height = sse_decode_u_32(deserializer);
    var var_spendableZat = sse_decode_u_64(deserializer);
    var var_totalZat = sse_decode_u_64(deserializer);
    return Balance(
      height: var_height,
      spendableZat: var_spendableZat,
      totalZat: var_totalZat,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  ZafeError sse_decode_box_autoadd_zafe_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_zafe_error(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  IdentityInfo sse_decode_identity_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_seeds = sse_decode_list_prim_u_8_strict(deserializer);
    var var_publicKeyHex = sse_decode_String(deserializer);
    return IdentityInfo(seeds: var_seeds, publicKeyHex: var_publicKeyHex);
  }

  @protected
  InviteInfo sse_decode_invite_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_threshold = sse_decode_u_16(deserializer);
    var var_members = sse_decode_u_16(deserializer);
    var var_creatorHex = sse_decode_String(deserializer);
    return InviteInfo(
      name: var_name,
      threshold: var_threshold,
      members: var_members,
      creatorHex: var_creatorHex,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<PaymentInfo> sse_decode_list_payment_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PaymentInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_payment_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<PaymentInput> sse_decode_list_payment_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PaymentInput>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_payment_input(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProposalInfo> sse_decode_list_proposal_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProposalInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_proposal_info(deserializer));
    }
    return ans_;
  }

  @protected
  MembershipInfo sse_decode_membership_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_members = sse_decode_list_String(deserializer);
    var var_sealed = sse_decode_bool(deserializer);
    var var_safetyNumber = sse_decode_String(deserializer);
    var var_isCreator = sse_decode_bool(deserializer);
    return MembershipInfo(
      members: var_members,
      sealed: var_sealed,
      safetyNumber: var_safetyNumber,
      isCreator: var_isCreator,
    );
  }

  @protected
  MyVote sse_decode_my_vote(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MyVote.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ZafeError? sse_decode_opt_box_autoadd_zafe_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_zafe_error(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PaymentInfo sse_decode_payment_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_String(deserializer);
    var var_amountZat = sse_decode_u_64(deserializer);
    var var_memo = sse_decode_String(deserializer);
    return PaymentInfo(
      address: var_address,
      amountZat: var_amountZat,
      memo: var_memo,
    );
  }

  @protected
  PaymentInput sse_decode_payment_input(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_String(deserializer);
    var var_amountZat = sse_decode_u_64(deserializer);
    var var_memo = sse_decode_String(deserializer);
    return PaymentInput(
      address: var_address,
      amountZat: var_amountZat,
      memo: var_memo,
    );
  }

  @protected
  ProposalInfo sse_decode_proposal_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_author = sse_decode_String(deserializer);
    var var_isMine = sse_decode_bool(deserializer);
    var var_payments = sse_decode_list_payment_info(deserializer);
    var var_totalZat = sse_decode_u_64(deserializer);
    var var_stage = sse_decode_proposal_stage(deserializer);
    var var_approvals = sse_decode_list_String(deserializer);
    var var_rejections = sse_decode_list_String(deserializer);
    var var_myVote = sse_decode_my_vote(deserializer);
    var var_threshold = sse_decode_u_16(deserializer);
    var var_rejectionThreshold = sse_decode_u_16(deserializer);
    var var_createdAt = sse_decode_u_64(deserializer);
    var var_txid = sse_decode_opt_String(deserializer);
    var var_signingStarted = sse_decode_bool(deserializer);
    var var_oneTap = sse_decode_bool(deserializer);
    var var_ready = sse_decode_bool(deserializer);
    var var_completedByMe = sse_decode_bool(deserializer);
    var var_autoSend = sse_decode_bool(deserializer);
    return ProposalInfo(
      id: var_id,
      author: var_author,
      isMine: var_isMine,
      payments: var_payments,
      totalZat: var_totalZat,
      stage: var_stage,
      approvals: var_approvals,
      rejections: var_rejections,
      myVote: var_myVote,
      threshold: var_threshold,
      rejectionThreshold: var_rejectionThreshold,
      createdAt: var_createdAt,
      txid: var_txid,
      signingStarted: var_signingStarted,
      oneTap: var_oneTap,
      ready: var_ready,
      completedByMe: var_completedByMe,
      autoSend: var_autoSend,
    );
  }

  @protected
  ProposalStage sse_decode_proposal_stage(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ProposalStage.values[inner];
  }

  @protected
  ReviewInfo sse_decode_review_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_verified = sse_decode_bool(deserializer);
    var var_problem = sse_decode_String(deserializer);
    var var_feeZat = sse_decode_u_64(deserializer);
    var var_changeZat = sse_decode_u_64(deserializer);
    var var_inputZat = sse_decode_u_64(deserializer);
    var var_spends = sse_decode_u_32(deserializer);
    var var_expiryHeight = sse_decode_u_32(deserializer);
    var var_tipHeight = sse_decode_u_32(deserializer);
    return ReviewInfo(
      verified: var_verified,
      problem: var_problem,
      feeZat: var_feeZat,
      changeZat: var_changeZat,
      inputZat: var_inputZat,
      spends: var_spends,
      expiryHeight: var_expiryHeight,
      tipHeight: var_tipHeight,
    );
  }

  @protected
  SendProgress sse_decode_send_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stage = sse_decode_send_stage(deserializer);
    var var_received = sse_decode_u_32(deserializer);
    var var_needed = sse_decode_u_32(deserializer);
    var var_txid = sse_decode_opt_String(deserializer);
    var var_error = sse_decode_opt_box_autoadd_zafe_error(deserializer);
    return SendProgress(
      stage: var_stage,
      received: var_received,
      needed: var_needed,
      txid: var_txid,
      error: var_error,
    );
  }

  @protected
  SendStage sse_decode_send_stage(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SendStage.values[inner];
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VaultSummary sse_decode_vault_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_network = sse_decode_String(deserializer);
    var var_address = sse_decode_String(deserializer);
    var var_threshold = sse_decode_u_16(deserializer);
    var var_members = sse_decode_list_String(deserializer);
    var var_birthdayHeight = sse_decode_u_32(deserializer);
    return VaultSummary(
      name: var_name,
      network: var_network,
      address: var_address,
      threshold: var_threshold,
      members: var_members,
      birthdayHeight: var_birthdayHeight,
    );
  }

  @protected
  ZafeError sse_decode_zafe_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_zafe_error_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    return ZafeError(kind: var_kind, message: var_message);
  }

  @protected
  ZafeErrorKind sse_decode_zafe_error_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ZafeErrorKind.values[inner];
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_send_progress_Sse(
    RustStreamSink<SendProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_send_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_address_check(AddressCheck self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.valid, serializer);
    sse_encode_String(self.reason, serializer);
  }

  @protected
  void sse_encode_approve_result(ApproveResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.signed, serializer);
    sse_encode_bool(self.completed, serializer);
    sse_encode_bool(self.autoSend, serializer);
  }

  @protected
  void sse_encode_balance(Balance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.height, serializer);
    sse_encode_u_64(self.spendableZat, serializer);
    sse_encode_u_64(self.totalZat, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_zafe_error(
    ZafeError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_zafe_error(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_identity_info(IdentityInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.seeds, serializer);
    sse_encode_String(self.publicKeyHex, serializer);
  }

  @protected
  void sse_encode_invite_info(InviteInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_16(self.threshold, serializer);
    sse_encode_u_16(self.members, serializer);
    sse_encode_String(self.creatorHex, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_payment_info(
    List<PaymentInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_payment_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_payment_input(
    List<PaymentInput> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_payment_input(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_proposal_info(
    List<ProposalInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_proposal_info(item, serializer);
    }
  }

  @protected
  void sse_encode_membership_info(
    MembershipInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.members, serializer);
    sse_encode_bool(self.sealed, serializer);
    sse_encode_String(self.safetyNumber, serializer);
    sse_encode_bool(self.isCreator, serializer);
  }

  @protected
  void sse_encode_my_vote(MyVote self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_zafe_error(
    ZafeError? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_zafe_error(self, serializer);
    }
  }

  @protected
  void sse_encode_payment_info(PaymentInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.address, serializer);
    sse_encode_u_64(self.amountZat, serializer);
    sse_encode_String(self.memo, serializer);
  }

  @protected
  void sse_encode_payment_input(PaymentInput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.address, serializer);
    sse_encode_u_64(self.amountZat, serializer);
    sse_encode_String(self.memo, serializer);
  }

  @protected
  void sse_encode_proposal_info(ProposalInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.author, serializer);
    sse_encode_bool(self.isMine, serializer);
    sse_encode_list_payment_info(self.payments, serializer);
    sse_encode_u_64(self.totalZat, serializer);
    sse_encode_proposal_stage(self.stage, serializer);
    sse_encode_list_String(self.approvals, serializer);
    sse_encode_list_String(self.rejections, serializer);
    sse_encode_my_vote(self.myVote, serializer);
    sse_encode_u_16(self.threshold, serializer);
    sse_encode_u_16(self.rejectionThreshold, serializer);
    sse_encode_u_64(self.createdAt, serializer);
    sse_encode_opt_String(self.txid, serializer);
    sse_encode_bool(self.signingStarted, serializer);
    sse_encode_bool(self.oneTap, serializer);
    sse_encode_bool(self.ready, serializer);
    sse_encode_bool(self.completedByMe, serializer);
    sse_encode_bool(self.autoSend, serializer);
  }

  @protected
  void sse_encode_proposal_stage(ProposalStage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_review_info(ReviewInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.verified, serializer);
    sse_encode_String(self.problem, serializer);
    sse_encode_u_64(self.feeZat, serializer);
    sse_encode_u_64(self.changeZat, serializer);
    sse_encode_u_64(self.inputZat, serializer);
    sse_encode_u_32(self.spends, serializer);
    sse_encode_u_32(self.expiryHeight, serializer);
    sse_encode_u_32(self.tipHeight, serializer);
  }

  @protected
  void sse_encode_send_progress(SendProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_send_stage(self.stage, serializer);
    sse_encode_u_32(self.received, serializer);
    sse_encode_u_32(self.needed, serializer);
    sse_encode_opt_String(self.txid, serializer);
    sse_encode_opt_box_autoadd_zafe_error(self.error, serializer);
  }

  @protected
  void sse_encode_send_stage(SendStage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_vault_summary(VaultSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.network, serializer);
    sse_encode_String(self.address, serializer);
    sse_encode_u_16(self.threshold, serializer);
    sse_encode_list_String(self.members, serializer);
    sse_encode_u_32(self.birthdayHeight, serializer);
  }

  @protected
  void sse_encode_zafe_error(ZafeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_zafe_error_kind(self.kind, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_zafe_error_kind(
    ZafeErrorKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }
}
