// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'names.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Live feedback while typing a backup passphrase.
PassphraseCheck checkBackupPassphrase({required String passphrase}) => RustLib
    .instance
    .api
    .crateApiBackupCheckBackupPassphrase(passphrase: passphrase);

/// 12 random words (128 bits): strong and writable on paper.
String suggestBackupPassphrase() =>
    RustLib.instance.api.crateApiBackupSuggestBackupPassphrase();

/// Encrypts this device's copy of a vault (Argon2id 64 MiB; takes a second or two), with
/// the local names this device gave the signers.
Future<ExportedBackup> exportVaultBackup({
  required List<int> seeds,
  required List<int> material,
  required String invite,
  required List<SignerName> names,
  required String passphrase,
}) => RustLib.instance.api.crateApiBackupExportVaultBackup(
  seeds: seeds,
  material: material,
  invite: invite,
  names: names,
  passphrase: passphrase,
);

/// Decrypts a backup (file bytes, or the pasted text form) and checks it: the identity must
/// be a member of the vault it restores.
Future<ImportedVault> importVaultBackup({
  required List<int> data,
  required String passphrase,
}) => RustLib.instance.api.crateApiBackupImportVaultBackup(
  data: data,
  passphrase: passphrase,
);

class ExportedBackup {
  /// The file contents.
  final Uint8List bytes;

  /// The same backup as text (`zafe-backup-v1:...`), for password managers.
  final String text;

  const ExportedBackup({required this.bytes, required this.text});

  @override
  int get hashCode => bytes.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportedBackup &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          text == other.text;
}

class ImportedVault {
  final String vaultId;
  final String name;
  final Uint8List identitySeeds;
  final Uint8List material;
  final String invite;

  /// Local signer names saved with the backup (empty for backups made before names were
  /// included).
  final List<SignerName> names;

  const ImportedVault({
    required this.vaultId,
    required this.name,
    required this.identitySeeds,
    required this.material,
    required this.invite,
    required this.names,
  });

  @override
  int get hashCode =>
      vaultId.hashCode ^
      name.hashCode ^
      identitySeeds.hashCode ^
      material.hashCode ^
      invite.hashCode ^
      names.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportedVault &&
          runtimeType == other.runtimeType &&
          vaultId == other.vaultId &&
          name == other.name &&
          identitySeeds == other.identitySeeds &&
          material == other.material &&
          invite == other.invite &&
          names == other.names;
}

class PassphraseCheck {
  final bool ok;

  /// Why it's too weak (empty when ok).
  final String hint;

  const PassphraseCheck({required this.ok, required this.hint});

  @override
  int get hashCode => ok.hashCode ^ hint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PassphraseCheck &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          hint == other.hint;
}
