// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Checks that a Zafe relay answers at `relay_url` (`GET /health`).
Future<void> checkRelay({required String relayUrl}) =>
    RustLib.instance.api.crateApiEndpointsCheckRelay(relayUrl: relayUrl);

/// Checks that lightwalletd answers at `lightwalletd_url` and serves `network_name`
/// (`main`, `test`, `regtest`). Returns its chain tip height.
Future<int> checkLightwalletd({
  required String lightwalletdUrl,
  required String networkName,
}) => RustLib.instance.api.crateApiEndpointsCheckLightwalletd(
  lightwalletdUrl: lightwalletdUrl,
  networkName: networkName,
);
