// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `invalid`, `new`, `version_kind`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

class ZafeError implements FrbException {
  final ZafeErrorKind kind;
  final String message;

  const ZafeError({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZafeError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

enum ZafeErrorKind {
  /// The relay or lightwalletd could not be reached.
  network,

  /// Waiting on other members or on sync; try again later.
  notReady,

  /// Other members did not answer in time; safe to retry.
  timeout,

  /// This device's independent check failed: never approve or sign.
  verification,

  /// The vault cannot cover the amount plus the fee.
  insufficientFunds,

  /// Bad address, amount, memo or invite.
  invalidInput,

  /// Data, a message or the relay comes from a newer version of Zafe: update the app.
  updateRequired,

  /// The relay is older than this app and must be updated by whoever runs it.
  relayOutdated,
  other,
}
