// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `status`, `watch_mempool_async`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `watch_mempool_with`

/// A new watch id; any watch started with an earlier id stops within ~100 ms.
int beginMempoolWatch() =>
    RustLib.instance.api.crateApiMempoolBeginMempoolWatch();

/// Stops the running watch (if any) within ~100 ms.
void stopMempoolWatch() =>
    RustLib.instance.api.crateApiMempoolStopMempoolWatch();

/// Watches the mempool for the vault until `watch_id` is stale (see the module docs).
/// Returns at once; the watch runs in the background and reports through `sink`, which
/// closes when it ends. Failures arrive as events, never as an error.
Stream<MempoolEvent> watchMempool({
  required int watchId,
  required String lightwalletdUrl,
  required String dbDir,
  required List<int> dbKey,
  required List<int> material,
}) => RustLib.instance.api.crateApiMempoolWatchMempool(
  watchId: watchId,
  lightwalletdUrl: lightwalletdUrl,
  dbDir: dbDir,
  dbKey: dbKey,
  material: material,
);

class MempoolEvent {
  final MempoolStatus status;

  /// Transaction id (hex, display order) for `Stored` / `StoreFailed`.
  final String? txid;
  final ZafeError? error;
  final int retryInSecs;

  const MempoolEvent({
    required this.status,
    this.txid,
    this.error,
    required this.retryInSecs,
  });

  @override
  int get hashCode =>
      status.hashCode ^ txid.hashCode ^ error.hashCode ^ retryInSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MempoolEvent &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          txid == other.txid &&
          error == other.error &&
          retryInSecs == other.retryInSecs;
}

enum MempoolStatus {
  /// Watching (after every (re)connect).
  connected,

  /// A vault transaction from the mempool was stored (`txid`): reload received payments.
  stored,

  /// Storing a vault transaction failed (`txid`, `error`); retried after the next block.
  storeFailed,

  /// lightwalletd could not be reached or the stream broke (`error`); retrying in
  /// `retry_in_secs`.
  disconnected,

  /// The watch could not start (`error`: bad material or key); it has ended.
  failed,
}
