// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_map`, `to_map`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// One local name: the signer's signing key (hex) and the name this device gave it.
class SignerName {
  final String keyHex;
  final String name;

  const SignerName({required this.keyHex, required this.name});

  @override
  int get hashCode => keyHex.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignerName &&
          runtimeType == other.runtimeType &&
          keyHex == other.keyHex &&
          name == other.name;
}
