// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `info`, `leader_dir`, `local_tip`, `memo_bytes`, `memo_text`, `nonce_store`, `parse_id`, `pool_store`, `request_file`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `send_with_progress`

/// Vault payments go to shielded (Orchard-receiver) unified addresses only.
AddressCheck checkAddress({
  required String networkName,
  required String address,
}) => RustLib.instance.api.crateApiProposalsCheckAddress(
  networkName: networkName,
  address: address,
);

/// Parses a ZEC amount ("1.5", "0,25") to zatoshis. `None` if malformed or above 8 decimals.
BigInt? parseZec({required String text}) =>
    RustLib.instance.api.crateApiProposalsParseZec(text: text);

/// Bytes a memo takes (the limit is 512).
int memoLength({required String memo}) =>
    RustLib.instance.api.crateApiProposalsMemoLength(memo: memo);

/// Every proposal in the vault log, newest first. Also keeps this device ready for
/// one-tap signing: tops up its pre-published commitments when they run low, and deletes
/// nonces of proposals that closed.
Future<List<ProposalInfo>> listProposals({
  required String relayUrl,
  required String stateDir,
  required List<int> seeds,
  required List<int> material,
}) => RustLib.instance.api.crateApiProposalsListProposals(
  relayUrl: relayUrl,
  stateDir: stateDir,
  seeds: seeds,
  material: material,
);

/// Syncs, builds the transaction from the vault's notes, and logs it as a proposal. Returns
/// the proposal id.
Future<String> proposePayment({
  required String relayUrl,
  required String lightwalletdUrl,
  required String dbDir,
  required List<int> seeds,
  required List<int> material,
  required List<PaymentInput> payments,
  required bool autoSend,
}) => RustLib.instance.api.crateApiProposalsProposePayment(
  relayUrl: relayUrl,
  lightwalletdUrl: lightwalletdUrl,
  dbDir: dbDir,
  seeds: seeds,
  material: material,
  payments: payments,
  autoSend: autoSend,
);

Future<ReviewInfo> reviewProposal({
  required String relayUrl,
  required String lightwalletdUrl,
  required String dbDir,
  required List<int> seeds,
  required List<int> material,
  required String proposalId,
}) => RustLib.instance.api.crateApiProposalsReviewProposal(
  relayUrl: relayUrl,
  lightwalletdUrl: lightwalletdUrl,
  dbDir: dbDir,
  seeds: seeds,
  material: material,
  proposalId: proposalId,
);

/// Verifies the proposal on this device and, only if it passes, approves it. For one-tap
/// proposals the approval also signs; see `ApproveResult`.
Future<ApproveResult> approveProposal({
  required String relayUrl,
  required String lightwalletdUrl,
  required String dbDir,
  required String stateDir,
  required List<int> seeds,
  required List<int> material,
  required String proposalId,
}) => RustLib.instance.api.crateApiProposalsApproveProposal(
  relayUrl: relayUrl,
  lightwalletdUrl: lightwalletdUrl,
  dbDir: dbDir,
  stateDir: stateDir,
  seeds: seeds,
  material: material,
  proposalId: proposalId,
);

Future<void> rejectProposal({
  required String relayUrl,
  required List<int> seeds,
  required List<int> material,
  required String proposalId,
}) => RustLib.instance.api.crateApiProposalsRejectProposal(
  relayUrl: relayUrl,
  seeds: seeds,
  material: material,
  proposalId: proposalId,
);

/// Answers signing requests for proposals this member approved (each is re-verified first).
/// Called on every poll. Returns how many were answered.
Future<int> answerSigningRequests({
  required String relayUrl,
  required String lightwalletdUrl,
  required String dbDir,
  required String stateDir,
  required List<int> seeds,
  required List<int> material,
}) => RustLib.instance.api.crateApiProposalsAnswerSigningRequests(
  relayUrl: relayUrl,
  lightwalletdUrl: lightwalletdUrl,
  dbDir: dbDir,
  stateDir: stateDir,
  seeds: seeds,
  material: material,
);

/// Leader: asks the approvers for signatures (once per proposal on this device), signs its
/// own part, collects the rest while proving, and broadcasts. On a timeout, call again: it
/// resumes the same signing round.
Stream<SendProgress> sendProposal({
  required String relayUrl,
  required String lightwalletdUrl,
  required String dbDir,
  required String stateDir,
  required List<int> seeds,
  required List<int> material,
  required String proposalId,
}) => RustLib.instance.api.crateApiProposalsSendProposal(
  relayUrl: relayUrl,
  lightwalletdUrl: lightwalletdUrl,
  dbDir: dbDir,
  stateDir: stateDir,
  seeds: seeds,
  material: material,
  proposalId: proposalId,
);

class AddressCheck {
  final bool valid;

  /// Why the address can't be paid (empty when valid).
  final String reason;

  const AddressCheck({required this.valid, required this.reason});

  @override
  int get hashCode => valid.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddressCheck &&
          runtimeType == other.runtimeType &&
          valid == other.valid &&
          reason == other.reason;
}

class ApproveResult {
  /// The approval carried this member's signatures (one tap).
  final bool signed;

  /// This approval completed the signatures: the proposal can be sent now.
  final bool completed;

  /// The proposer asked for the completing member to send right away.
  final bool autoSend;

  const ApproveResult({
    required this.signed,
    required this.completed,
    required this.autoSend,
  });

  @override
  int get hashCode => signed.hashCode ^ completed.hashCode ^ autoSend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApproveResult &&
          runtimeType == other.runtimeType &&
          signed == other.signed &&
          completed == other.completed &&
          autoSend == other.autoSend;
}

enum MyVote { none, approved, rejected }

class PaymentInfo {
  final String address;
  final BigInt amountZat;
  final String memo;

  const PaymentInfo({
    required this.address,
    required this.amountZat,
    required this.memo,
  });

  @override
  int get hashCode => address.hashCode ^ amountZat.hashCode ^ memo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaymentInfo &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          amountZat == other.amountZat &&
          memo == other.memo;
}

class PaymentInput {
  final String address;
  final BigInt amountZat;
  final String memo;

  const PaymentInput({
    required this.address,
    required this.amountZat,
    required this.memo,
  });

  @override
  int get hashCode => address.hashCode ^ amountZat.hashCode ^ memo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaymentInput &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          amountZat == other.amountZat &&
          memo == other.memo;
}

class ProposalInfo {
  final String id;
  final String author;
  final bool isMine;
  final List<PaymentInfo> payments;
  final BigInt totalZat;
  final ProposalStage stage;
  final List<String> approvals;
  final List<String> rejections;
  final MyVote myVote;
  final int threshold;
  final int rejectionThreshold;

  /// Proposer's clock (unix seconds, display only).
  final BigInt createdAt;
  final String? txid;

  /// This device already sent a signing request for it (it can resume collecting).
  final bool signingStarted;

  /// Signed at approval time (one tap): approvals carry the signatures.
  final bool oneTap;

  /// Some signer group has every signature: any member can send it now, alone.
  final bool ready;

  /// This member's approval completed the signatures (it sends when `auto_send`).
  final bool completedByMe;

  /// The proposer asked for it to be sent as soon as the signatures are complete.
  final bool autoSend;

  const ProposalInfo({
    required this.id,
    required this.author,
    required this.isMine,
    required this.payments,
    required this.totalZat,
    required this.stage,
    required this.approvals,
    required this.rejections,
    required this.myVote,
    required this.threshold,
    required this.rejectionThreshold,
    required this.createdAt,
    this.txid,
    required this.signingStarted,
    required this.oneTap,
    required this.ready,
    required this.completedByMe,
    required this.autoSend,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      author.hashCode ^
      isMine.hashCode ^
      payments.hashCode ^
      totalZat.hashCode ^
      stage.hashCode ^
      approvals.hashCode ^
      rejections.hashCode ^
      myVote.hashCode ^
      threshold.hashCode ^
      rejectionThreshold.hashCode ^
      createdAt.hashCode ^
      txid.hashCode ^
      signingStarted.hashCode ^
      oneTap.hashCode ^
      ready.hashCode ^
      completedByMe.hashCode ^
      autoSend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProposalInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          author == other.author &&
          isMine == other.isMine &&
          payments == other.payments &&
          totalZat == other.totalZat &&
          stage == other.stage &&
          approvals == other.approvals &&
          rejections == other.rejections &&
          myVote == other.myVote &&
          threshold == other.threshold &&
          rejectionThreshold == other.rejectionThreshold &&
          createdAt == other.createdAt &&
          txid == other.txid &&
          signingStarted == other.signingStarted &&
          oneTap == other.oneTap &&
          ready == other.ready &&
          completedByMe == other.completedByMe &&
          autoSend == other.autoSend;
}

enum ProposalStage {
  /// Waiting for approvals.
  open,

  /// Enough approvals; waiting for a member to collect signatures and send.
  approved,
  rejected,
  cancelled,
  sent,
}

/// This device's independent check of a proposal (spec §9.3).
class ReviewInfo {
  /// Whether the transaction pays exactly the proposed payments, with change back to
  /// the vault and the standard fee. If false, `problem` says why: do not approve.
  final bool verified;
  final String problem;
  final BigInt feeZat;
  final BigInt changeZat;
  final BigInt inputZat;
  final int spends;
  final int expiryHeight;
  final int tipHeight;

  const ReviewInfo({
    required this.verified,
    required this.problem,
    required this.feeZat,
    required this.changeZat,
    required this.inputZat,
    required this.spends,
    required this.expiryHeight,
    required this.tipHeight,
  });

  @override
  int get hashCode =>
      verified.hashCode ^
      problem.hashCode ^
      feeZat.hashCode ^
      changeZat.hashCode ^
      inputZat.hashCode ^
      spends.hashCode ^
      expiryHeight.hashCode ^
      tipHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewInfo &&
          runtimeType == other.runtimeType &&
          verified == other.verified &&
          problem == other.problem &&
          feeZat == other.feeZat &&
          changeZat == other.changeZat &&
          inputZat == other.inputZat &&
          spends == other.spends &&
          expiryHeight == other.expiryHeight &&
          tipHeight == other.tipHeight;
}

class SendProgress {
  final SendStage stage;
  final int received;
  final int needed;
  final String? txid;
  final ZafeError? error;

  const SendProgress({
    required this.stage,
    required this.received,
    required this.needed,
    this.txid,
    this.error,
  });

  @override
  int get hashCode =>
      stage.hashCode ^
      received.hashCode ^
      needed.hashCode ^
      txid.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendProgress &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          received == other.received &&
          needed == other.needed &&
          txid == other.txid &&
          error == other.error;
}

enum SendStage {
  /// Signing requests are out; the transaction proof is being built meanwhile.
  collecting,
  sent,

  /// Not sent; `error` says why. Retrying resumes the same signing round.
  failed,
}
