// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The vault's received payments, newest first. Reads the wallet database created by
/// `sync_vault`; before the first sync there is none and the list is empty.
Future<List<ReceivedInfo>> listReceived({
  required String dbDir,
  required List<int> material,
}) => RustLib.instance.api.crateApiReceivedListReceived(
  dbDir: dbDir,
  material: material,
);

/// One incoming payment (a transaction that pays the vault and spends none of its notes).
class ReceivedInfo {
  /// Transaction id (hex, display order).
  final String txid;
  final BigInt amountZat;

  /// 0 while unmined.
  final int minedHeight;

  /// Unix seconds of the mining block; 0 when unknown (unmined, or block not scanned).
  final int blockTimeSecs;

  /// Blocks on top of (and including) the mining block at the wallet's synced height; 0
  /// while unmined.
  final int confirmations;

  /// Text memos of the received outputs, joined by blank lines (empty if none).
  final String memo;

  /// A mining reward (coinbase); spendable after 100 confirmations.
  final bool isCoinbase;

  const ReceivedInfo({
    required this.txid,
    required this.amountZat,
    required this.minedHeight,
    required this.blockTimeSecs,
    required this.confirmations,
    required this.memo,
    required this.isCoinbase,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      amountZat.hashCode ^
      minedHeight.hashCode ^
      blockTimeSecs.hashCode ^
      confirmations.hashCode ^
      memo.hashCode ^
      isCoinbase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceivedInfo &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          amountZat == other.amountZat &&
          minedHeight == other.minedHeight &&
          blockTimeSecs == other.blockTimeSecs &&
          confirmations == other.confirmations &&
          memo == other.memo &&
          isCoinbase == other.isCoinbase;
}
