// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `identity`, `material`, `network`, `runtime`

IdentityInfo generateIdentity() =>
    RustLib.instance.api.crateApiVaultGenerateIdentity();

/// The public key (hex) of an identity, e.g. to mark "You" in member lists.
String identityPublicKey({required List<int> seeds}) =>
    RustLib.instance.api.crateApiVaultIdentityPublicKey(seeds: seeds);

InviteInfo parseInvite({required String invite}) =>
    RustLib.instance.api.crateApiVaultParseInvite(invite: invite);

/// Creates a vault mailbox on the relay and returns the invite string to share.
Future<String> createVault({
  required String relayUrl,
  required List<int> seeds,
  required String name,
  required int threshold,
  required int members,
}) => RustLib.instance.api.crateApiVaultCreateVault(
  relayUrl: relayUrl,
  seeds: seeds,
  name: name,
  threshold: threshold,
  members: members,
);

Future<void> joinVault({
  required String relayUrl,
  required List<int> seeds,
  required String invite,
}) => RustLib.instance.api.crateApiVaultJoinVault(
  relayUrl: relayUrl,
  seeds: seeds,
  invite: invite,
);

Future<MembershipInfo> vaultMembership({
  required String relayUrl,
  required List<int> seeds,
  required String invite,
}) => RustLib.instance.api.crateApiVaultVaultMembership(
  relayUrl: relayUrl,
  seeds: seeds,
  invite: invite,
);

/// Creator only: freezes membership once everyone has joined.
Future<void> sealVault({
  required String relayUrl,
  required List<int> seeds,
  required String invite,
}) => RustLib.instance.api.crateApiVaultSealVault(
  relayUrl: relayUrl,
  seeds: seeds,
  invite: invite,
);

/// Runs key generation. Blocks until every member finishes (or `timeout_secs`). Returns the
/// vault material (secret: store it in secure storage).
Future<Uint8List> runKeygen({
  required String relayUrl,
  required String lightwalletdUrl,
  required String networkName,
  required List<int> seeds,
  required String invite,
  required String confirmedSafetyNumber,
  required int timeoutSecs,
}) => RustLib.instance.api.crateApiVaultRunKeygen(
  relayUrl: relayUrl,
  lightwalletdUrl: lightwalletdUrl,
  networkName: networkName,
  seeds: seeds,
  invite: invite,
  confirmedSafetyNumber: confirmedSafetyNumber,
  timeoutSecs: timeoutSecs,
);

VaultSummary vaultSummary({required List<int> material}) =>
    RustLib.instance.api.crateApiVaultVaultSummary(material: material);

/// Syncs the vault wallet (creating its database under `db_dir` on first use).
Future<Balance> syncVault({
  required String dbDir,
  required String lightwalletdUrl,
  required List<int> material,
}) => RustLib.instance.api.crateApiVaultSyncVault(
  dbDir: dbDir,
  lightwalletdUrl: lightwalletdUrl,
  material: material,
);

class Balance {
  final int height;
  final BigInt spendableZat;
  final BigInt totalZat;

  const Balance({
    required this.height,
    required this.spendableZat,
    required this.totalZat,
  });

  @override
  int get hashCode =>
      height.hashCode ^ spendableZat.hashCode ^ totalZat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Balance &&
          runtimeType == other.runtimeType &&
          height == other.height &&
          spendableZat == other.spendableZat &&
          totalZat == other.totalZat;
}

/// A new member identity. `seeds` (64 bytes) is secret: store it in secure storage.
class IdentityInfo {
  final Uint8List seeds;
  final String publicKeyHex;

  const IdentityInfo({required this.seeds, required this.publicKeyHex});

  @override
  int get hashCode => seeds.hashCode ^ publicKeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityInfo &&
          runtimeType == other.runtimeType &&
          seeds == other.seeds &&
          publicKeyHex == other.publicKeyHex;
}

class InviteInfo {
  final String name;
  final int threshold;
  final int members;
  final String creatorHex;

  const InviteInfo({
    required this.name,
    required this.threshold,
    required this.members,
    required this.creatorHex,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      threshold.hashCode ^
      members.hashCode ^
      creatorHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InviteInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          threshold == other.threshold &&
          members == other.members &&
          creatorHex == other.creatorHex;
}

class MembershipInfo {
  final List<String> members;
  final bool sealed;
  final String safetyNumber;
  final bool isCreator;

  const MembershipInfo({
    required this.members,
    required this.sealed,
    required this.safetyNumber,
    required this.isCreator,
  });

  @override
  int get hashCode =>
      members.hashCode ^
      sealed.hashCode ^
      safetyNumber.hashCode ^
      isCreator.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MembershipInfo &&
          runtimeType == other.runtimeType &&
          members == other.members &&
          sealed == other.sealed &&
          safetyNumber == other.safetyNumber &&
          isCreator == other.isCreator;
}

class VaultSummary {
  final String name;
  final String network;
  final String address;
  final int threshold;
  final List<String> members;
  final int birthdayHeight;

  const VaultSummary({
    required this.name,
    required this.network,
    required this.address,
    required this.threshold,
    required this.members,
    required this.birthdayHeight,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      network.hashCode ^
      address.hashCode ^
      threshold.hashCode ^
      members.hashCode ^
      birthdayHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultSummary &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          network == other.network &&
          address == other.address &&
          threshold == other.threshold &&
          members == other.members &&
          birthdayHeight == other.birthdayHeight;
}
