// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `backoff`, `failed`, `of`, `runs`, `watch_loop`, `watches`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Watches`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `watch_vault_with`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// Watches the vault for activity until `stop_vault_watch(watch_id)` or a watch with a
/// higher `watch_id` starts. Returns at once; events arrive on the stream, failures
/// included (they are events, not errors). The stream closes when the watch ends.
Stream<VaultActivity> watchVault({
  required String relayUrl,
  required List<int> seeds,
  required List<int> material,
  required PlatformInt64 watchId,
}) => RustLib.instance.api.crateApiWatchWatchVault(
  relayUrl: relayUrl,
  seeds: seeds,
  material: material,
  watchId: watchId,
);

/// Stops the watch `watch_id` and any older one (also one whose start hasn't arrived
/// yet).
void stopVaultWatch({required PlatformInt64 watchId}) =>
    RustLib.instance.api.crateApiWatchStopVaultWatch(watchId: watchId);

class VaultActivity {
  final VaultActivityKind kind;
  final ZafeError? error;
  final int retryInSecs;

  const VaultActivity({
    required this.kind,
    this.error,
    required this.retryInSecs,
  });

  @override
  int get hashCode => kind.hashCode ^ error.hashCode ^ retryInSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultActivity &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          error == other.error &&
          retryInSecs == other.retryInSecs;
}

enum VaultActivityKind {
  /// The watch reaches the relay (first time, or again after failures): activity will
  /// be reported as it happens.
  connected,

  /// The vault log grew or something was delivered to this member: refresh.
  activity,

  /// The relay has no long polls (older relay): the watch has ended; keep polling.
  unsupported,

  /// An attempt failed (`error`); the watch retries in `retry_in_secs`. When
  /// `retry_in_secs` is 0 the watch has ended (e.g. a version mismatch or bad input).
  failed,
}
